cmsdefine([], function () {
    return {
        ADMINISTRATION_DOMAIN_PARAMETER_NAME: "administrationUrl",
        MVC_FRAME_AUTHENTICATED_EVENT_NAME: "MVC_FRAME_AUTHENTICATED_EVENT_NAME",
        ADMIN_FRAME_REQUEST_AUTHENTICATION_EVENT_NAME: "ADMIN_FRAME_REQUEST_AUTHENTICATION_EVENT_NAME"
    };
});
