cmsdefine([], function () {
    return {
        ADMINISTRATION_DOMAIN_PARAMETER_NAME: "administrationUrl",
        MVC_FRAME_AUTHENTICATED_EVENT_NAME_PREFIX: "MVC_FRAME_AUTHENTICATED_EVENT_NAME_PREFIX",
        ADMIN_FRAME_REQUEST_AUTHENTICATION_EVENT_NAME: "ADMIN_FRAME_REQUEST_AUTHENTICATION_EVENT_NAME",
        AUTHENTICATE_MVC_FRAME_POST_MESSAGE: "AUTHENTICATE_MVC_FRAME_POST_MESSAGE",
        AUTHENTICATED_MVC_FRAME_POST_MESSAGE: "AUTHENTICATED_MVC_FRAME_POST_MESSAGE"
    };
});
