//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CMSWebParts_Chat_ChatWebpart {
    
    /// <summary>
    /// lblError control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMS.Base.Web.UI.LocalizedLabel lblError;
    
    /// <summary>
    /// pnlChatWebpart control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatWebpart;
    
    /// <summary>
    /// pnlChatWebpartLeftCol control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatWebpartLeftCol;
    
    /// <summary>
    /// Login control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatLogin Login;
    
    /// <summary>
    /// OnlineUsers control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatOnlineUsers OnlineUsers;
    
    /// <summary>
    /// SearchOnlineUsers control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatSearchOnlineUsers SearchOnlineUsers;
    
    /// <summary>
    /// Rooms control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatRooms Rooms;
    
    /// <summary>
    /// RoomUsers control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatRoomUsers RoomUsers;
    
    /// <summary>
    /// pnlChatWebpartRightCol control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatWebpartRightCol;
    
    /// <summary>
    /// pnlChatWebpartHeader control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.Panel pnlChatWebpartHeader;
    
    /// <summary>
    /// RoomName control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatRoomName RoomName;
    
    /// <summary>
    /// RoomLeave control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatLeaveRoom RoomLeave;
    
    /// <summary>
    /// Notification control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatNotification Notification;
    
    /// <summary>
    /// RoomMessageSend control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatMessageSend RoomMessageSend;
    
    /// <summary>
    /// Errors control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatErrors Errors;
    
    /// <summary>
    /// RoomMessages control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSWebParts_Chat_ChatRoomMessages RoomMessages;
}
