//--------------------------------------------------------------------------------------------------
// <auto-generated>
//
//     This code was generated by code generator tool.
//
//     To customize the code use your own partial class. For more info about how to use and customize
//     the generated code see the documentation at https://docs.xperience.io/.
//
// </auto-generated>
//--------------------------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using CMS;
using CMS.Base;
using CMS.Helpers;
using CMS.DataEngine;
using CMS.DocumentEngine;
using CMS.DocumentEngine.Types.MedioClinic;

[assembly: RegisterDocumentType(BasicPageWithUrlSlug.CLASS_NAME, typeof(BasicPageWithUrlSlug))]

namespace CMS.DocumentEngine.Types.MedioClinic
{
	/// <summary>
	/// Represents a content item of type BasicPageWithUrlSlug.
	/// </summary>
	public partial class BasicPageWithUrlSlug : TreeNode
	{
		#region "Constants and variables"

		/// <summary>
		/// The name of the data class.
		/// </summary>
		public const string CLASS_NAME = "MedioClinic.BasicPageWithUrlSlug";


		/// <summary>
		/// The instance of the class that provides extended API for working with BasicPageWithUrlSlug fields.
		/// </summary>
		private readonly BasicPageWithUrlSlugFields mFields;

		#endregion


		#region "Properties"

		/// <summary>
		/// BasicPageWithUrlSlugID.
		/// </summary>
		[DatabaseIDField]
		public int BasicPageWithUrlSlugID
		{
			get
			{
				return ValidationHelper.GetInteger(GetValue("BasicPageWithUrlSlugID"), 0);
			}
			set
			{
				SetValue("BasicPageWithUrlSlugID", value);
			}
		}


		/// <summary>
		/// URL slug.
		/// </summary>
		[DatabaseField]
		public string UrlSlug
		{
			get
			{
				return ValidationHelper.GetString(GetValue("UrlSlug"), @"");
			}
			set
			{
				SetValue("UrlSlug", value);
			}
		}


		/// <summary>
		/// Gets an object that provides extended API for working with BasicPageWithUrlSlug fields.
		/// </summary>
		[RegisterProperty]
		public BasicPageWithUrlSlugFields Fields
		{
			get
			{
				return mFields;
			}
		}


		/// <summary>
		/// Provides extended API for working with BasicPageWithUrlSlug fields.
		/// </summary>
		[RegisterAllProperties]
		public partial class BasicPageWithUrlSlugFields : AbstractHierarchicalObject<BasicPageWithUrlSlugFields>
		{
			/// <summary>
			/// The content item of type BasicPageWithUrlSlug that is a target of the extended API.
			/// </summary>
			private readonly BasicPageWithUrlSlug mInstance;


			/// <summary>
			/// Initializes a new instance of the <see cref="BasicPageWithUrlSlugFields" /> class with the specified content item of type BasicPageWithUrlSlug.
			/// </summary>
			/// <param name="instance">The content item of type BasicPageWithUrlSlug that is a target of the extended API.</param>
			public BasicPageWithUrlSlugFields(BasicPageWithUrlSlug instance)
			{
				mInstance = instance;
			}


			/// <summary>
			/// BasicPageWithUrlSlugID.
			/// </summary>
			public int ID
			{
				get
				{
					return mInstance.BasicPageWithUrlSlugID;
				}
				set
				{
					mInstance.BasicPageWithUrlSlugID = value;
				}
			}


			/// <summary>
			/// URL slug.
			/// </summary>
			public string UrlSlug
			{
				get
				{
					return mInstance.UrlSlug;
				}
				set
				{
					mInstance.UrlSlug = value;
				}
			}
		}

		#endregion


		#region "Constructors"

		/// <summary>
		/// Initializes a new instance of the <see cref="BasicPageWithUrlSlug" /> class.
		/// </summary>
		public BasicPageWithUrlSlug() : base(CLASS_NAME)
		{
			mFields = new BasicPageWithUrlSlugFields(this);
		}

		#endregion
	}
}