//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated. 
// </auto-generated>
//------------------------------------------------------------------------------



public partial class CMSModules_SocialMarketing_Pages_InsightsReport {
    
    /// <summary>
    /// ucGraphPreLoader control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSModules_WebAnalytics_Controls_GraphPreLoader ucGraphPreLoader;
    
    /// <summary>
    /// ucGraphType control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::CMSModules_WebAnalytics_Controls_SelectGraphTypeAndPeriod ucGraphType;
    
    /// <summary>
    /// pnlDisplayReport control.
    /// </summary>
    /// <remarks>
    /// Auto-generated field.
    /// To modify move field declaration from designer file to code-behind file.
    /// </remarks>
    protected global::System.Web.UI.WebControls.PlaceHolder pnlDisplayReport;
}
